<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="edm" nsURI="http://odata.org/edm" nsPrefix="edm">
  <eClassifiers xsi:type="ecore:EClass" name="ODService">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schemas" upperBound="-1"
        eType="#//ODSchema" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODSchema" eSuperTypes="#//ODAnnotable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityContainer" eType="#//ODEntityContainer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityTypes" upperBound="-1"
        eType="#//ODEntityType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complexTypes" upperBound="-1"
        eType="#//ODComplexType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumTypes" upperBound="-1"
        eType="#//ODEnumType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinitions" upperBound="-1"
        eType="#//ODTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1"
        eType="#//ODTerm" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveTypes" upperBound="-1"
        eType="#//ODPrimitiveType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODEntityContainer" eSuperTypes="#//ODNamedElement #//ODAnnotable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitySets" upperBound="-1"
        eType="#//ODEntitySet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singletons" upperBound="-1"
        eType="#//ODSingleton" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODType" eSuperTypes="#//ODNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ODAnnotable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//ODAnnotation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODStructuralType" eSuperTypes="#//ODType #//ODAnnotable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" eType="#//ODStructuralType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ODElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODEntityType" eSuperTypes="#//ODStructuralType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" upperBound="-1" eType="#//ODPropertyKeyRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODComplexType" eSuperTypes="#//ODStructuralType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ODPrimitiveType" eSuperTypes="#//ODType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ODEnumType" eSuperTypes="#//ODPrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Members" upperBound="-1"
        eType="#//ODMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODProperty" eSuperTypes="#//ODElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimeType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unicode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ODType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multivalued" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODNavigationProperty" eSuperTypes="#//ODElement #//ODAnnotable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containsTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partner" eType="#//ODNavigationProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODElement" eSuperTypes="#//TypedElement #//ODNamedElement #//ODAnnotable"/>
  <eClassifiers xsi:type="ecore:EClass" name="ODExposedEntityType" eSuperTypes="#//ODNamedElement #//ODAnnotable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityType" eType="#//ODEntityType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigationPropertyBindings"
        upperBound="-1" eType="#//ODNavigationPropertyBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODEntitySet" eSuperTypes="#//ODExposedEntityType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includeInServiceDocument"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODSingleton" eSuperTypes="#//ODExposedEntityType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ODNavigationPropertyBinding">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//ODTerm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODTerm" eSuperTypes="#//ODNamedElement #//ODAnnotable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appliesTo" upperBound="-1"
        eType="#//ODTermTarget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ODType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ODTermTarget">
    <eLiterals name="undefined"/>
    <eLiterals name="schema" value="1"/>
    <eLiterals name="entityType" value="2"/>
    <eLiterals name="property" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODTypeDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="underlyingType" eType="#//ODPrimitiveType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unicode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODMember" eSuperTypes="#//ODNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ODPropertyKeyRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//ODProperty"/>
  </eClassifiers>
</ecore:EPackage>
